# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4534af83305de9fa5d232acdd6223ba691684c2f1c661a7774569a6573cff3a80332641de147db07c1874528031081e8ece730898eeb5804ca4df6b692792474

test:
  secret_key_base: 23dd527c79c06f5c7fd3ad800acaa1a84fc8fab01f7795e4a112f729b5089c2054ec0a4921a3b13852939982433152154f6f3d7e12a6003893b8bdf37c3879dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
